[package]
name = "spring-tdf"
version = "0.1.0"
edition = "2024"
description = "Parser for Spring RTS engine TDF (Tag Definition Format) files"

[dependencies]
better_default = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lib]
doctest = false
