[package]
name = "spring-cob"
version = "0.1.0"
edition = "2024"
description = "Parser and virtual machine for Spring RTS engine COB animation scripts"

[dependencies]
binrw = "0.15.1"
smallvec = "1.15.1"
strum = { version = "0.28.0", features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lib]
doctest = false
