//! Embed the web map catalog at compile time.
//!
//! Web builds have no filesystem, so `pick_map` can't scan
//! `assets/maps/` at runtime. Instead we list every `.kpmap` present in
//! the directory at build time — the deploy workflow bakes the maps
//! before `trunk build`, so the embedded list always matches what got
//! copied into the Pages artifact. Native builds ignore this and keep
//! scanning the directory at runtime, where `.sd7`/`.sdz` sources work
//! too.

use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=assets/maps");

    let maps_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/maps");
    let mut names: Vec<String> = std::fs::read_dir(&maps_dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("kpmap") {
                path.file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
            } else {
                None
            }
        })
        .collect();
    names.sort();
    names.dedup();

    let entries: Vec<String> = names.iter().map(|n| format!("\"{n}\"")).collect();
    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         #[allow(dead_code)]\npub const WEB_MAP_CATALOG: &[&str] = &[{}];\n",
        entries.join(", ")
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = Path::new(&out_dir).join("web_map_catalog.rs");
    std::fs::write(out_path, generated).expect("write web_map_catalog.rs");
}
