[package]
name = "kernel-panic"
version = "0.1.0"
edition = "2024"

[dependencies]
spring-tdf = { path = "../spring-tdf" }
spring-map = { path = "../spring-map" }
spring-unit-mesh = { path = "../spring-unit-mesh" }
spring-cob = { path = "../spring-cob" }
bevy = { version = "0.18", features = ["serialize", "debug"] }
thiserror = { workspace = true }
